#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef ADRENDERKIT_SWIFT_H
#define ADRENDERKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AdRenderKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

typedef SWIFT_ENUM(NSInteger, AdChoicePosition, open) {
  AdChoicePositionTopRight = 0,
  AdChoicePositionTopLeft = 1,
  AdChoicePositionBottomRight = 2,
  AdChoicePositionBottomLeft = 3,
};

SWIFT_CLASS("_TtC11AdRenderKit15AdCreativeEvent")
@interface AdCreativeEvent : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP11AdRenderKit25AdCreativeEventSubscriber_")
@protocol AdCreativeEventSubscriber
- (void)onEvent:(AdCreativeEvent * _Nonnull)adCreativeEvent;
@end

SWIFT_PROTOCOL("_TtP11AdRenderKit23AdCreativeEventDelegate_")
@protocol AdCreativeEventDelegate <AdCreativeEventSubscriber>
@end

typedef SWIFT_ENUM(NSInteger, AdCreativeFormat, open) {
  AdCreativeFormatHtml = 0,
  AdCreativeFormatImage = 1,
  AdCreativeFormatVast = 2,
  AdCreativeFormatVideo = 3,
};

SWIFT_CLASS("_TtC11AdRenderKit15AdCreativeModel")
@interface AdCreativeModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
@class ViewabilitySettings;
@protocol MacroApplier;
@class InjectionScript;
enum PlacementType : NSInteger;
enum Position : NSInteger;
@class FullScreenConfig;
@class VideoSettings;
SWIFT_CLASS("_TtC11AdRenderKit22AdCreativeModelFactory")
@interface AdCreativeModelFactory : NSObject
+ (AdCreativeModel * _Nonnull)createHtmlAdCreativeWithContentUrl:(NSString * _Nullable)contentUrl adm:(NSString * _Nullable)adm baseUrl:(NSString * _Nullable)baseUrl viewabilitySettings:(ViewabilitySettings * _Nonnull)viewabilitySettings syncTag:(NSString * _Nullable)syncTag omScript:(NSString * _Nullable)omScript omVendorkey:(NSString * _Nullable)omVendorkey omVerificationParameters:(NSString * _Nullable)omVerificationParameters omVerificationScript:(NSString * _Nullable)omVerificationScript adchoiceImage:(NSString * _Nullable)adchoiceImage adchoiceUrl:(NSString * _Nullable)adchoiceUrl adchoicePosition:(enum AdChoicePosition)adchoicePosition size:(CGSize)size macroApplier:(id <MacroApplier> _Nullable)macroApplier injectionScripts:(NSArray<InjectionScript *> * _Nonnull)injectionScripts isMRAID:(BOOL)isMRAID placementType:(enum PlacementType)placementType closeImageUrl:(NSString * _Nullable)closeImageUrl closeButtonPosition:(enum Position)closeButtonPosition closeAppearanceDelay:(NSInteger)closeAppearanceDelay shouldAutoClose:(BOOL)shouldAutoClose autoCloseDurationInSec:(int64_t)autoCloseDurationInSec fullScreenConfig:(FullScreenConfig * _Nullable)fullScreenConfig backgroundColorCode:(NSString * _Nullable)backgroundColorCode SWIFT_WARN_UNUSED_RESULT;
+ (AdCreativeModel * _Nonnull)createImageAdCreativeWithContentUrl:(NSString * _Nullable)contentUrl adm:(NSString * _Nullable)adm baseUrl:(NSString * _Nullable)baseUrl viewabilitySettings:(ViewabilitySettings * _Nonnull)viewabilitySettings syncTag:(NSString * _Nullable)syncTag omScript:(NSString * _Nullable)omScript omVendorkey:(NSString * _Nullable)omVendorkey omVerificationParameters:(NSString * _Nullable)omVerificationParameters omVerificationScript:(NSString * _Nullable)omVerificationScript adchoiceImage:(NSString * _Nullable)adchoiceImage adchoiceUrl:(NSString * _Nullable)adchoiceUrl adchoicePosition:(enum AdChoicePosition)adchoicePosition size:(CGSize)size macroApplier:(id <MacroApplier> _Nullable)macroApplier backgroundColorCode:(NSString * _Nullable)backgroundColorCode SWIFT_WARN_UNUSED_RESULT;
+ (AdCreativeModel * _Nonnull)createVastAdCreativeWithContentUrl:(NSString * _Nullable)contentUrl adm:(NSString * _Nullable)adm baseUrl:(NSString * _Nullable)baseUrl viewabilitySettings:(ViewabilitySettings * _Nonnull)viewabilitySettings videoSettings:(VideoSettings * _Nonnull)videoSettings syncTag:(NSString * _Nullable)syncTag omScript:(NSString * _Nullable)omScript omVendorkey:(NSString * _Nullable)omVendorkey omVerificationParameters:(NSString * _Nullable)omVerificationParameters omVerificationScript:(NSString * _Nullable)omVerificationScript adchoiceImage:(NSString * _Nullable)adchoiceImage adchoiceUrl:(NSString * _Nullable)adchoiceUrl adchoicePosition:(enum AdChoicePosition)adchoicePosition macroApplier:(id <MacroApplier> _Nullable)macroApplier closeImageUrl:(NSString * _Nullable)closeImageUrl closeButtonPosition:(enum Position)closeButtonPosition closeAppearanceDelay:(NSInteger)closeAppearanceDelay shouldAutoClose:(BOOL)shouldAutoClose autoCloseDurationInSec:(int64_t)autoCloseDurationInSec fullScreenConfig:(FullScreenConfig * _Nullable)fullScreenConfig backgroundColorCode:(NSString * _Nullable)backgroundColorCode SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIViewController;
@protocol UserAgentProviderProtocol;
@protocol OMStaticAd;
SWIFT_CLASS("_TtC11AdRenderKit18AdCreativeRenderer")
@interface AdCreativeRenderer : NSObject
@property (nonatomic, readonly, strong) AdCreativeModel * _Nonnull adCreativeModel;
@property (nonatomic, weak) id <AdCreativeEventDelegate> _Nullable delegate;
- (nonnull instancetype)initWithAdCreativeModel:(AdCreativeModel * _Nonnull)adCreativeModel viewControllerForPresentingModals:(UIViewController * _Nullable)viewControllerForPresentingModals userAgentProvider:(id <UserAgentProviderProtocol> _Nullable)userAgentProvider omStaticAd:(id <OMStaticAd> _Nullable)omStaticAd;
- (void)load;
- (void)destroy;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC11AdRenderKit16FullScreenHeader")
@interface FullScreenHeader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC11AdRenderKit13AppOpenHeader")
@interface AppOpenHeader : FullScreenHeader
- (nonnull instancetype)initWithAppName:(NSString * _Nonnull)appName appIcon:(NSString * _Nonnull)appIcon adtag:(NSString * _Nonnull)adtag actionText:(NSString * _Nonnull)actionText headerViewHeightInDP:(NSInteger)headerViewHeightInDP adTagViewHeightInDP:(NSInteger)adTagViewHeightInDP separatorHeightInDP:(NSInteger)separatorHeightInDP bottomMarginInDP:(NSInteger)bottomMarginInDP OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURL;
SWIFT_CLASS("_TtC11AdRenderKit10ClickEvent")
@interface ClickEvent : AdCreativeEvent
@property (nonatomic, readonly, copy) NSURL * _Nonnull clickUrl;
@end

SWIFT_CLASS("_TtC11AdRenderKit10CloseEvent")
@interface CloseEvent : AdCreativeEvent
@end

@class UIView;
SWIFT_PROTOCOL("_TtP11AdRenderKit13ContainerView_")
@protocol ContainerView
- (void)addWithView:(UIView * _Nonnull)view;
@end

SWIFT_CLASS("_TtC11AdRenderKit17FailedToLoadEvent")
@interface FailedToLoadEvent : AdCreativeEvent
@property (nonatomic, readonly) NSError * _Nonnull error;
@end

SWIFT_CLASS("_TtC11AdRenderKit17FailedToShowEvent")
@interface FailedToShowEvent : AdCreativeEvent
@property (nonatomic, readonly) NSError * _Nonnull error;
@end

SWIFT_CLASS("_TtC11AdRenderKit28FullScreenAdCreativeRenderer")
@interface FullScreenAdCreativeRenderer : AdCreativeRenderer
- (void)showWithViewControllerForPresentingModals:(UIViewController * _Nullable)viewControllerForPresentingModals;
- (void)destroy;
@end

SWIFT_CLASS("_TtC11AdRenderKit16FullScreenConfig")
@interface FullScreenConfig : NSObject
- (nonnull instancetype)initWithFullScreenHeader:(FullScreenHeader * _Nullable)fullScreenHeader OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ViewabilityTracker;
SWIFT_CLASS("_TtC11AdRenderKit15ImpressionEvent")
@interface ImpressionEvent : AdCreativeEvent
@property (nonatomic, readonly, strong) ViewabilityTracker * _Nonnull viewabilityTracker;
@end

typedef SWIFT_ENUM(NSInteger, InjectionLocation, open) {
  InjectionLocationHead = 0,
  InjectionLocationBodyStart = 1,
  InjectionLocationBodyEnd = 2,
};

SWIFT_CLASS("_TtC11AdRenderKit15InjectionScript")
@interface InjectionScript : NSObject
@property (nonatomic, readonly) enum InjectionLocation location;
@property (nonatomic, readonly, copy) NSString * _Nullable url;
@property (nonatomic, readonly, copy) NSString * _Nullable content;
- (nonnull instancetype)initWithLocation:(enum InjectionLocation)location url:(NSString * _Nullable)url content:(NSString * _Nullable)content OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC11AdRenderKit24InlineAdCreativeRenderer")
@interface InlineAdCreativeRenderer : AdCreativeRenderer
- (void)renderWithView:(id <ContainerView> _Nonnull)view;
- (void)destroy;
@end

SWIFT_PROTOCOL("_TtP11AdRenderKit12MacroApplier_")
@protocol MacroApplier
- (NSString * _Nonnull)applyTo:(NSString * _Nonnull)inputString SWIFT_WARN_UNUSED_RESULT;
@end

@class WKWebView;
SWIFT_PROTOCOL("_TtP11AdRenderKit10OMStaticAd_")
@protocol OMStaticAd
- (BOOL)initializeHTMLAdCreativeOMSDKWithAdView:(UIView * _Nonnull)adView webView:(WKWebView * _Nonnull)webView content:(NSString * _Nonnull)content contentUrl:(NSString * _Nonnull)contentUrl error:(NSError * _Nullable * _Nullable)error;
- (BOOL)initializeVASTAdCreativeOMSDKWithAdView:(UIView * _Nonnull)adView content:(NSString * _Nonnull)content contentUrl:(NSString * _Nonnull)contentUrl error:(NSError * _Nullable * _Nullable)error;
- (BOOL)startSessionAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)finishSessionAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)loadedAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)loadedVastWithAutoPlay:(BOOL)autoPlay error:(NSError * _Nullable * _Nullable)error;
- (BOOL)impressionOccurredAndReturnError:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)injectScriptContentIntoHTML:(NSString * _Nonnull)html error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (void)destroySession;
- (BOOL)isSessionDestroyed SWIFT_WARN_UNUSED_RESULT;
- (BOOL)videoPauseAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoResumeAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoBufferStartAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoBufferFinishAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoAdUserInteractionAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoVolumeChangeTo:(float)volume error:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoStartWithDuration:(NSTimeInterval)duration mediaPlayerVolume:(float)mediaPlayerVolume error:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoFirstQuartileAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoMidpointAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoThirdQuartileAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoCompleteAndReturnError:(NSError * _Nullable * _Nullable)error;
@end

typedef SWIFT_ENUM(NSInteger, PlacementType, open) {
  PlacementTypeInline = 0,
  PlacementTypeFullscreen = 1,
};

typedef SWIFT_ENUM(NSInteger, Position, open) {
  PositionUndefined = 0,
  PositionTopLeft = 1,
  PositionTopCenter = 2,
  PositionTopRight = 3,
  PositionCenter = 4,
  PositionBottomLeft = 5,
  PositionBottomCenter = 6,
  PositionBottomRight = 7,
  PositionCustom = 8,
};

SWIFT_CLASS("_TtC11AdRenderKit19ReadyToDisplayEvent")
@interface ReadyToDisplayEvent : AdCreativeEvent
@end

@class UIImage;
SWIFT_CLASS("_TtC11AdRenderKit23RendererImageDownloader")
@interface RendererImageDownloader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)imageWithUrl:(NSString * _Nonnull)url blured:(BOOL)blured completion:(void (^ _Nonnull)(UIImage * _Nullable))completion;
@end

SWIFT_CLASS("_TtC11AdRenderKit23VASTAdBufferFinishEvent")
@interface VASTAdBufferFinishEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit22VASTAdBufferStartEvent")
@interface VASTAdBufferStartEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit16VASTAdClickEvent")
@interface VASTAdClickEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit19VASTAdCompleteEvent")
@interface VASTAdCompleteEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit24VASTAdFirstQuartileEvent")
@interface VASTAdFirstQuartileEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit19VASTAdMidpointEvent")
@interface VASTAdMidpointEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit16VASTAdPauseEvent")
@interface VASTAdPauseEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit17VASTAdResumeEvent")
@interface VASTAdResumeEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit16VASTAdStartEvent")
@interface VASTAdStartEvent : AdCreativeEvent
@property (nonatomic, readonly) NSTimeInterval duration;
@property (nonatomic, readonly) float volume;
@end

SWIFT_CLASS("_TtC11AdRenderKit24VASTAdThirdQuartileEvent")
@interface VASTAdThirdQuartileEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit23VASTAdVolumeChangeEvent")
@interface VASTAdVolumeChangeEvent : AdCreativeEvent
@property (nonatomic, readonly) float volume;
@end

@class AVPlayer;
SWIFT_CLASS("_TtC11AdRenderKit14VideoPreloader")
@interface VideoPreloader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (AVPlayer * _Nullable)getVideoPlayer SWIFT_WARN_UNUSED_RESULT;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
@end

@class NSNumber;
SWIFT_CLASS("_TtC11AdRenderKit13VideoSettings")
@interface VideoSettings : NSObject
@property (nonatomic, readonly) BOOL autoPlay;
@property (nonatomic, readonly, copy) NSString * _Nonnull audio;
@property (nonatomic, readonly) BOOL blur;
@property (nonatomic, readonly, strong) NSNumber * _Nonnull radius;
@property (nonatomic, readonly, strong) NSNumber * _Nonnull opacity;
- (nonnull instancetype)initWithAutoPlay:(BOOL)autoPlay audio:(NSString * _Nonnull)audio blur:(BOOL)blur radius:(NSNumber * _Nonnull)radius opacity:(NSNumber * _Nonnull)opacity OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC11AdRenderKit19ViewabilitySettings")
@interface ViewabilitySettings : NSObject
- (nonnull instancetype)initWithWidth:(float)width height:(float)height percent:(float)percent period:(float)period alpha:(float)alpha maxViewabilityTime:(NSInteger)maxViewabilityTime viewabilityUrl:(NSString * _Nullable)viewabilityUrl OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC11AdRenderKit22ViewabilityTrackResult")
@interface ViewabilityTrackResult : NSObject
@property (nonatomic, readonly) float visiblePeriod;
@property (nonatomic, readonly) float totalPeriod;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC11AdRenderKit18ViewabilityTracker")
@interface ViewabilityTracker : NSObject
- (void)track:(void (^ _Nonnull)(ViewabilityTrackResult * _Nonnull))onComplete;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef ADRENDERKIT_SWIFT_H
#define ADRENDERKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AdRenderKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

typedef SWIFT_ENUM(NSInteger, AdChoicePosition, open) {
  AdChoicePositionTopRight = 0,
  AdChoicePositionTopLeft = 1,
  AdChoicePositionBottomRight = 2,
  AdChoicePositionBottomLeft = 3,
};

SWIFT_CLASS("_TtC11AdRenderKit15AdCreativeEvent")
@interface AdCreativeEvent : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP11AdRenderKit25AdCreativeEventSubscriber_")
@protocol AdCreativeEventSubscriber
- (void)onEvent:(AdCreativeEvent * _Nonnull)adCreativeEvent;
@end

SWIFT_PROTOCOL("_TtP11AdRenderKit23AdCreativeEventDelegate_")
@protocol AdCreativeEventDelegate <AdCreativeEventSubscriber>
@end

typedef SWIFT_ENUM(NSInteger, AdCreativeFormat, open) {
  AdCreativeFormatHtml = 0,
  AdCreativeFormatImage = 1,
  AdCreativeFormatVast = 2,
  AdCreativeFormatVideo = 3,
};

SWIFT_CLASS("_TtC11AdRenderKit15AdCreativeModel")
@interface AdCreativeModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
@class ViewabilitySettings;
@protocol MacroApplier;
@class InjectionScript;
enum PlacementType : NSInteger;
enum Position : NSInteger;
@class FullScreenConfig;
@class VideoSettings;
SWIFT_CLASS("_TtC11AdRenderKit22AdCreativeModelFactory")
@interface AdCreativeModelFactory : NSObject
+ (AdCreativeModel * _Nonnull)createHtmlAdCreativeWithContentUrl:(NSString * _Nullable)contentUrl adm:(NSString * _Nullable)adm baseUrl:(NSString * _Nullable)baseUrl viewabilitySettings:(ViewabilitySettings * _Nonnull)viewabilitySettings syncTag:(NSString * _Nullable)syncTag omScript:(NSString * _Nullable)omScript omVendorkey:(NSString * _Nullable)omVendorkey omVerificationParameters:(NSString * _Nullable)omVerificationParameters omVerificationScript:(NSString * _Nullable)omVerificationScript adchoiceImage:(NSString * _Nullable)adchoiceImage adchoiceUrl:(NSString * _Nullable)adchoiceUrl adchoicePosition:(enum AdChoicePosition)adchoicePosition size:(CGSize)size macroApplier:(id <MacroApplier> _Nullable)macroApplier injectionScripts:(NSArray<InjectionScript *> * _Nonnull)injectionScripts isMRAID:(BOOL)isMRAID placementType:(enum PlacementType)placementType closeImageUrl:(NSString * _Nullable)closeImageUrl closeButtonPosition:(enum Position)closeButtonPosition closeAppearanceDelay:(NSInteger)closeAppearanceDelay shouldAutoClose:(BOOL)shouldAutoClose autoCloseDurationInSec:(int64_t)autoCloseDurationInSec fullScreenConfig:(FullScreenConfig * _Nullable)fullScreenConfig backgroundColorCode:(NSString * _Nullable)backgroundColorCode SWIFT_WARN_UNUSED_RESULT;
+ (AdCreativeModel * _Nonnull)createImageAdCreativeWithContentUrl:(NSString * _Nullable)contentUrl adm:(NSString * _Nullable)adm baseUrl:(NSString * _Nullable)baseUrl viewabilitySettings:(ViewabilitySettings * _Nonnull)viewabilitySettings syncTag:(NSString * _Nullable)syncTag omScript:(NSString * _Nullable)omScript omVendorkey:(NSString * _Nullable)omVendorkey omVerificationParameters:(NSString * _Nullable)omVerificationParameters omVerificationScript:(NSString * _Nullable)omVerificationScript adchoiceImage:(NSString * _Nullable)adchoiceImage adchoiceUrl:(NSString * _Nullable)adchoiceUrl adchoicePosition:(enum AdChoicePosition)adchoicePosition size:(CGSize)size macroApplier:(id <MacroApplier> _Nullable)macroApplier backgroundColorCode:(NSString * _Nullable)backgroundColorCode SWIFT_WARN_UNUSED_RESULT;
+ (AdCreativeModel * _Nonnull)createVastAdCreativeWithContentUrl:(NSString * _Nullable)contentUrl adm:(NSString * _Nullable)adm baseUrl:(NSString * _Nullable)baseUrl viewabilitySettings:(ViewabilitySettings * _Nonnull)viewabilitySettings videoSettings:(VideoSettings * _Nonnull)videoSettings syncTag:(NSString * _Nullable)syncTag omScript:(NSString * _Nullable)omScript omVendorkey:(NSString * _Nullable)omVendorkey omVerificationParameters:(NSString * _Nullable)omVerificationParameters omVerificationScript:(NSString * _Nullable)omVerificationScript adchoiceImage:(NSString * _Nullable)adchoiceImage adchoiceUrl:(NSString * _Nullable)adchoiceUrl adchoicePosition:(enum AdChoicePosition)adchoicePosition macroApplier:(id <MacroApplier> _Nullable)macroApplier closeImageUrl:(NSString * _Nullable)closeImageUrl closeButtonPosition:(enum Position)closeButtonPosition closeAppearanceDelay:(NSInteger)closeAppearanceDelay shouldAutoClose:(BOOL)shouldAutoClose autoCloseDurationInSec:(int64_t)autoCloseDurationInSec fullScreenConfig:(FullScreenConfig * _Nullable)fullScreenConfig backgroundColorCode:(NSString * _Nullable)backgroundColorCode SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIViewController;
@protocol UserAgentProviderProtocol;
@protocol OMStaticAd;
SWIFT_CLASS("_TtC11AdRenderKit18AdCreativeRenderer")
@interface AdCreativeRenderer : NSObject
@property (nonatomic, readonly, strong) AdCreativeModel * _Nonnull adCreativeModel;
@property (nonatomic, weak) id <AdCreativeEventDelegate> _Nullable delegate;
- (nonnull instancetype)initWithAdCreativeModel:(AdCreativeModel * _Nonnull)adCreativeModel viewControllerForPresentingModals:(UIViewController * _Nullable)viewControllerForPresentingModals userAgentProvider:(id <UserAgentProviderProtocol> _Nullable)userAgentProvider omStaticAd:(id <OMStaticAd> _Nullable)omStaticAd;
- (void)load;
- (void)destroy;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC11AdRenderKit16FullScreenHeader")
@interface FullScreenHeader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC11AdRenderKit13AppOpenHeader")
@interface AppOpenHeader : FullScreenHeader
- (nonnull instancetype)initWithAppName:(NSString * _Nonnull)appName appIcon:(NSString * _Nonnull)appIcon adtag:(NSString * _Nonnull)adtag actionText:(NSString * _Nonnull)actionText headerViewHeightInDP:(NSInteger)headerViewHeightInDP adTagViewHeightInDP:(NSInteger)adTagViewHeightInDP separatorHeightInDP:(NSInteger)separatorHeightInDP bottomMarginInDP:(NSInteger)bottomMarginInDP OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURL;
SWIFT_CLASS("_TtC11AdRenderKit10ClickEvent")
@interface ClickEvent : AdCreativeEvent
@property (nonatomic, readonly, copy) NSURL * _Nonnull clickUrl;
@end

SWIFT_CLASS("_TtC11AdRenderKit10CloseEvent")
@interface CloseEvent : AdCreativeEvent
@end

@class UIView;
SWIFT_PROTOCOL("_TtP11AdRenderKit13ContainerView_")
@protocol ContainerView
- (void)addWithView:(UIView * _Nonnull)view;
@end

SWIFT_CLASS("_TtC11AdRenderKit17FailedToLoadEvent")
@interface FailedToLoadEvent : AdCreativeEvent
@property (nonatomic, readonly) NSError * _Nonnull error;
@end

SWIFT_CLASS("_TtC11AdRenderKit17FailedToShowEvent")
@interface FailedToShowEvent : AdCreativeEvent
@property (nonatomic, readonly) NSError * _Nonnull error;
@end

SWIFT_CLASS("_TtC11AdRenderKit28FullScreenAdCreativeRenderer")
@interface FullScreenAdCreativeRenderer : AdCreativeRenderer
- (void)showWithViewControllerForPresentingModals:(UIViewController * _Nullable)viewControllerForPresentingModals;
- (void)destroy;
@end

SWIFT_CLASS("_TtC11AdRenderKit16FullScreenConfig")
@interface FullScreenConfig : NSObject
- (nonnull instancetype)initWithFullScreenHeader:(FullScreenHeader * _Nullable)fullScreenHeader OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ViewabilityTracker;
SWIFT_CLASS("_TtC11AdRenderKit15ImpressionEvent")
@interface ImpressionEvent : AdCreativeEvent
@property (nonatomic, readonly, strong) ViewabilityTracker * _Nonnull viewabilityTracker;
@end

typedef SWIFT_ENUM(NSInteger, InjectionLocation, open) {
  InjectionLocationHead = 0,
  InjectionLocationBodyStart = 1,
  InjectionLocationBodyEnd = 2,
};

SWIFT_CLASS("_TtC11AdRenderKit15InjectionScript")
@interface InjectionScript : NSObject
@property (nonatomic, readonly) enum InjectionLocation location;
@property (nonatomic, readonly, copy) NSString * _Nullable url;
@property (nonatomic, readonly, copy) NSString * _Nullable content;
- (nonnull instancetype)initWithLocation:(enum InjectionLocation)location url:(NSString * _Nullable)url content:(NSString * _Nullable)content OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC11AdRenderKit24InlineAdCreativeRenderer")
@interface InlineAdCreativeRenderer : AdCreativeRenderer
- (void)renderWithView:(id <ContainerView> _Nonnull)view;
- (void)destroy;
@end

SWIFT_PROTOCOL("_TtP11AdRenderKit12MacroApplier_")
@protocol MacroApplier
- (NSString * _Nonnull)applyTo:(NSString * _Nonnull)inputString SWIFT_WARN_UNUSED_RESULT;
@end

@class WKWebView;
SWIFT_PROTOCOL("_TtP11AdRenderKit10OMStaticAd_")
@protocol OMStaticAd
- (BOOL)initializeHTMLAdCreativeOMSDKWithAdView:(UIView * _Nonnull)adView webView:(WKWebView * _Nonnull)webView content:(NSString * _Nonnull)content contentUrl:(NSString * _Nonnull)contentUrl error:(NSError * _Nullable * _Nullable)error;
- (BOOL)initializeVASTAdCreativeOMSDKWithAdView:(UIView * _Nonnull)adView content:(NSString * _Nonnull)content contentUrl:(NSString * _Nonnull)contentUrl error:(NSError * _Nullable * _Nullable)error;
- (BOOL)startSessionAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)finishSessionAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)loadedAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)loadedVastWithAutoPlay:(BOOL)autoPlay error:(NSError * _Nullable * _Nullable)error;
- (BOOL)impressionOccurredAndReturnError:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nullable)injectScriptContentIntoHTML:(NSString * _Nonnull)html error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (void)destroySession;
- (BOOL)isSessionDestroyed SWIFT_WARN_UNUSED_RESULT;
- (BOOL)videoPauseAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoResumeAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoBufferStartAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoBufferFinishAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoAdUserInteractionAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoVolumeChangeTo:(float)volume error:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoStartWithDuration:(NSTimeInterval)duration mediaPlayerVolume:(float)mediaPlayerVolume error:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoFirstQuartileAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoMidpointAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoThirdQuartileAndReturnError:(NSError * _Nullable * _Nullable)error;
- (BOOL)videoCompleteAndReturnError:(NSError * _Nullable * _Nullable)error;
@end

typedef SWIFT_ENUM(NSInteger, PlacementType, open) {
  PlacementTypeInline = 0,
  PlacementTypeFullscreen = 1,
};

typedef SWIFT_ENUM(NSInteger, Position, open) {
  PositionUndefined = 0,
  PositionTopLeft = 1,
  PositionTopCenter = 2,
  PositionTopRight = 3,
  PositionCenter = 4,
  PositionBottomLeft = 5,
  PositionBottomCenter = 6,
  PositionBottomRight = 7,
  PositionCustom = 8,
};

SWIFT_CLASS("_TtC11AdRenderKit19ReadyToDisplayEvent")
@interface ReadyToDisplayEvent : AdCreativeEvent
@end

@class UIImage;
SWIFT_CLASS("_TtC11AdRenderKit23RendererImageDownloader")
@interface RendererImageDownloader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)imageWithUrl:(NSString * _Nonnull)url blured:(BOOL)blured completion:(void (^ _Nonnull)(UIImage * _Nullable))completion;
@end

SWIFT_CLASS("_TtC11AdRenderKit23VASTAdBufferFinishEvent")
@interface VASTAdBufferFinishEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit22VASTAdBufferStartEvent")
@interface VASTAdBufferStartEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit16VASTAdClickEvent")
@interface VASTAdClickEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit19VASTAdCompleteEvent")
@interface VASTAdCompleteEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit24VASTAdFirstQuartileEvent")
@interface VASTAdFirstQuartileEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit19VASTAdMidpointEvent")
@interface VASTAdMidpointEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit16VASTAdPauseEvent")
@interface VASTAdPauseEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit17VASTAdResumeEvent")
@interface VASTAdResumeEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit16VASTAdStartEvent")
@interface VASTAdStartEvent : AdCreativeEvent
@property (nonatomic, readonly) NSTimeInterval duration;
@property (nonatomic, readonly) float volume;
@end

SWIFT_CLASS("_TtC11AdRenderKit24VASTAdThirdQuartileEvent")
@interface VASTAdThirdQuartileEvent : AdCreativeEvent
@end

SWIFT_CLASS("_TtC11AdRenderKit23VASTAdVolumeChangeEvent")
@interface VASTAdVolumeChangeEvent : AdCreativeEvent
@property (nonatomic, readonly) float volume;
@end

@class AVPlayer;
SWIFT_CLASS("_TtC11AdRenderKit14VideoPreloader")
@interface VideoPreloader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (AVPlayer * _Nullable)getVideoPlayer SWIFT_WARN_UNUSED_RESULT;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
@end

@class NSNumber;
SWIFT_CLASS("_TtC11AdRenderKit13VideoSettings")
@interface VideoSettings : NSObject
@property (nonatomic, readonly) BOOL autoPlay;
@property (nonatomic, readonly, copy) NSString * _Nonnull audio;
@property (nonatomic, readonly) BOOL blur;
@property (nonatomic, readonly, strong) NSNumber * _Nonnull radius;
@property (nonatomic, readonly, strong) NSNumber * _Nonnull opacity;
- (nonnull instancetype)initWithAutoPlay:(BOOL)autoPlay audio:(NSString * _Nonnull)audio blur:(BOOL)blur radius:(NSNumber * _Nonnull)radius opacity:(NSNumber * _Nonnull)opacity OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC11AdRenderKit19ViewabilitySettings")
@interface ViewabilitySettings : NSObject
- (nonnull instancetype)initWithWidth:(float)width height:(float)height percent:(float)percent period:(float)period alpha:(float)alpha maxViewabilityTime:(NSInteger)maxViewabilityTime viewabilityUrl:(NSString * _Nullable)viewabilityUrl OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC11AdRenderKit22ViewabilityTrackResult")
@interface ViewabilityTrackResult : NSObject
@property (nonatomic, readonly) float visiblePeriod;
@property (nonatomic, readonly) float totalPeriod;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC11AdRenderKit18ViewabilityTracker")
@interface ViewabilityTracker : NSObject
- (void)track:(void (^ _Nonnull)(ViewabilityTrackResult * _Nonnull))onComplete;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
